import { ThumbsDown, ThumbsUp, Volume2 } from "lucide-react";
import { CopyBox } from "./CopyBox";
import { SwingoMark } from "./SwingoLogo";

export type ChatMessage = {
  id: string;
  role: string;
  content: string;
  image_url?: string | null;
  feedback?: number | null;
};

export function MessageCard({
  message,
  onFeedback,
  onSpeak,
}: {
  message: ChatMessage;
  onFeedback: (value: 1 | -1) => void;
  onSpeak: (text: string) => void;
}) {
  const isUser = message.role === "user";

  if (isUser) {
    return (
      <div className="animate-rise flex justify-end">
        <div className="max-w-[85%] rounded-2xl rounded-br-md bg-primary px-4 py-2.5 text-sm leading-relaxed text-primary-foreground shadow-[var(--shadow-soft)]">
          {message.content}
        </div>
      </div>
    );
  }

  return (
    <div className="animate-rise space-y-2">
      <div className="flex items-start gap-2.5">
        <SwingoMark className="mt-0.5 h-6 w-6 shrink-0" />
        <div className="min-w-0 flex-1 space-y-3">
          {message.image_url ? (
            <img
              src={message.image_url}
              alt="Generated by Swingo"
              className="w-full max-w-sm rounded-2xl border border-border"
            />
          ) : null}
          {message.content ? (
            <div className="whitespace-pre-wrap break-words text-[15px] leading-relaxed text-foreground">
              {message.content}
            </div>
          ) : null}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2 pl-9">
        <button
          type="button"
          aria-label="Like"
          onClick={() => onFeedback(1)}
          className={`rounded-full border border-border p-1.5 transition-colors ${
            message.feedback === 1 ? "border-accent text-accent" : "text-muted-foreground"
          }`}
        >
          <ThumbsUp className="h-3.5 w-3.5" />
        </button>
        <button
          type="button"
          aria-label="Dislike"
          onClick={() => onFeedback(-1)}
          className={`rounded-full border border-border p-1.5 transition-colors ${
            message.feedback === -1 ? "border-danger text-danger" : "text-muted-foreground"
          }`}
        >
          <ThumbsDown className="h-3.5 w-3.5" />
        </button>
        <CopyBox text={message.content} />
        <button
          type="button"
          aria-label="Read aloud"
          onClick={() => onSpeak(message.content)}
          className="rounded-full border border-border p-1.5 text-muted-foreground transition-colors hover:text-foreground"
        >
          <Volume2 className="h-3.5 w-3.5" />
        </button>
      </div>
    </div>
  );
}
